repository_type: pipeline

nf_core_version: 3.5.1

lint: {}

template:
  org: nf-core
  name: readmapping
  description: Map reads to databases using BWA-MEM2
  author: timrozday-mgnify
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
